In [1]:
import numpy as np
array1 = np.arange(12)
array1.size
array1.shape

(12,)

In [2]:
# 改變ndarray的形狀
array2 = array1.reshape((3, 4))
print(array2)
array2[2,1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


np.int64(9)

In [ ]:
array1.reshape((12,1))